# My page
> Criando a minha primeira página de Blog com o Jupyter Notebook
- toc: false
- branch: master
- badges: false
- comments: false
- author: Veronica
- categories: [blog]

In [11]:
import pandas as pd
import numpy as np

In [12]:
data = np.random.randint(0,500,(3,5))
data

array([[468,  33,  12, 127,  77],
       [474, 214, 454, 173, 346],
       [ 59, 373, 252, 320,  54]])

In [17]:
Cb1 = pd.DataFrame(data)
Cb1

     0    1    2    3    4
0  468   33   12  127   77
1  474  214  454  173  346
2   59  373  252  320   54

In [20]:
#hide_input Cb2 = pd.DataFrame(data)
#Cb2

In [21]:
#hide Cb3 = pd.DataFrame(data)
Cb3

     0    1    2    3    4
0  468   33   12  127   77
1  474  214  454  173  346
2   59  373  252  320   54