# My page
> Criando a minha primeira página de Blog com o Jupyter Notebook
- toc: false
- branch: master
- badges: false
- comments: false
- author: Veronica
- categories: [blog]

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = np.random.randint(0,500,(3,5))
data

array([[119, 483,  66, 205, 173],
       [ 17,  49, 246, 446, 412],
       [284, 169, 389,  20,  61]])

In [3]:
Cb1 = pd.DataFrame(data)
Cb1

     0    1    2    3    4
0  119  483   66  205  173
1   17   49  246  446  412
2  284  169  389   20   61

In [6]:
#hide_input Cb2 = pd.DataFrame(data)
#Cb2

In [8]:
#hide Ca3 = pd.DataFrame(data)
Ca3

     0    1    2    3    4
0  119  483   66  205  173
1   17   49  246  446  412
2  284  169  389   20   61